// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartEventPlatformWeb.Data;

#nullable disable

namespace SmartEventPlatformWeb.Migrations
{
    [DbContext(typeof(SmartPlatformDbContext))]
    [Migration("20260329223557_SeedEventRoles")]
    partial class SeedEventRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RegistrationFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EventId");

                    b.HasIndex("LocationId");

                    b.ToTable("EventSpeakersParticipations", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.EventRole", b =>
                {
                    b.Property<long>("EventRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventRoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventRoleId");

                    b.ToTable("EventRoles", (string)null);

                    b.HasData(
                        new
                        {
                            EventRoleId = 1L,
                            Name = "Main Speaker"
                        },
                        new
                        {
                            EventRoleId = 2L,
                            Name = "Guest Speaker"
                        },
                        new
                        {
                            EventRoleId = 3L,
                            Name = "Moderator"
                        },
                        new
                        {
                            EventRoleId = 4L,
                            Name = "Panelist"
                        });
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.EventSpeaker", b =>
                {
                    b.Property<long>("EventSpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventSpeakerId"));

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeakerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("EventSpeakerId");

                    b.HasIndex("EventRoleId");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("EventId", "SpeakerId", "Time")
                        .IsUnique();

                    b.ToTable("EventSpeakers", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Speaker", b =>
                {
                    b.Property<long>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SpeakerId"));

                    b.Property<string>("ExpertiseAreas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Event", b =>
                {
                    b.HasOne("SmartEventPlatformWeb.Domains.Location", "Location")
                        .WithMany("EventSpeakersParticipations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.EventSpeaker", b =>
                {
                    b.HasOne("SmartEventPlatformWeb.Domains.Event", "Event")
                        .WithMany("EventSpeakers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEventPlatformWeb.Domains.EventRole", "EventRole")
                        .WithMany("EventSpeakers")
                        .HasForeignKey("EventRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartEventPlatformWeb.Domains.Speaker", "Speaker")
                        .WithMany("EventSpeakers")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventRole");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Event", b =>
                {
                    b.Navigation("EventSpeakers");
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.EventRole", b =>
                {
                    b.Navigation("EventSpeakers");
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Location", b =>
                {
                    b.Navigation("EventSpeakersParticipations");
                });

            modelBuilder.Entity("SmartEventPlatformWeb.Domains.Speaker", b =>
                {
                    b.Navigation("EventSpeakers");
                });
#pragma warning restore 612, 618
        }
    }
}
