// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartEventPlatform.DirectoryService.Data;

#nullable disable

namespace SmartEventPlatform.DirectoryService.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20260616015943_EventSpeakerIdFix")]
    partial class EventSpeakerIdFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartEventPlatform.DirectoryService.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LocationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatform.DirectoryService.Models.LocationUsageTracker", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.HasKey("EventId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationUsageTrackers", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatform.DirectoryService.Models.ProcessedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatform.DirectoryService.Models.Speaker", b =>
                {
                    b.Property<long>("SpeakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SpeakerId"));

                    b.Property<string>("ExpertiseAreas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SpeakerId");

                    b.ToTable("Speakers", (string)null);
                });

            modelBuilder.Entity("SmartEventPlatform.DirectoryService.Models.SpeakerUsageTracker", b =>
                {
                    b.Property<long>("EventSpeakerId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpeakerId")
                        .HasColumnType("bigint");

                    b.HasKey("EventSpeakerId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("SpeakerUsageTrackers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
